import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const { colleges, criteria } = await req.json();

    if (!colleges || !Array.isArray(colleges) || colleges.length === 0) {
      return NextResponse.json(
        { error: "Colleges data is required for a verdict" },
        { status: 400 }
      );
    }

    // 1. Build the system-level instruction prompt for structural safety
    const prompt = `
      You are an expert academic advisor. Compare the following colleges based on these user preferences: ${criteria || "General Overview, Placements, and Campus Life"}.
      
      Colleges data: ${JSON.stringify(colleges)}

      You MUST respond with a valid JSON object matching this EXACT structural schema. Do not wrap the JSON in markdown code blocks like \`\`\`json. 

      Required JSON Schema:
      {
        "winner": "Name of the overall recommended college",
        "verdict": "A comprehensive summary explaining why this college is the winner based on the criteria.",
        "breakdown": [
          {
            "criterion": "Criterion Name (e.g., Placements)",
            "analysis": "Comparative breakdown for this specific criterion between the colleges."
          }
        ],
        "prosCons": {
          "collegeName1": {
            "pros": ["Pro 1", "Pro 2"],
            "cons": ["Con 1", "Con 2"]
          },
          "collegeName2": {
            "pros": ["Pro 1", "Pro 2"],
            "cons": ["Con 1", "Con 2"]
          }
        }
      }
    `;

    // 2. Safely grab the API Key from environment variables
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error("Missing GEMINI_API_KEY in environment configuration.");
      return NextResponse.json(
        { error: "AI comparison service is currently unconfigured." },
        { status: 500 }
      );
    }

    // 3. Dispatch the fetch to the standard Google Gemini API endpoint
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }],
            },
          ],
          generationConfig: {
            responseMimeType: "application/json", // Hard-forces Gemini to reply in strict JSON format
            temperature: 0.2,
          },
        }),
      }
    );

    const data = await response.json();

    if (!response.ok) {
      console.error("Gemini API Error Response:", data);
      return NextResponse.json(
        { error: "Failed to generate AI verdict from Gemini" },
        { status: 500 }
      );
    }

    // 4. Safely extract text from the unique Google response payload tree
    const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim();

    if (!rawText) {
      return NextResponse.json(
        { error: "Empty response generated by AI service" },
        { status: 500 }
      );
    }

    // 5. Parse the raw text string directly into an object to deliver clean JSON to your frontend
    const parsedVerdict = JSON.parse(rawText);
    return NextResponse.json(parsedVerdict);

  } catch (error: any) {
    console.error("Error inside compare/verdict route:", error);
    return NextResponse.json(
      { error: "An internal server error occurred while analyzing the comparison." },
      { status: 500 }
    );
  }
}